#joli_blog:
    #resource: "@JoliBlogBundle/Controller/"
    #type:     annotation
    #prefix:   /blog

propose_post:
    path: /blog/propose
    defaults:
        { _controller: JoliBlogBundle:Propose:propose }

posts:
    path: /blog/{page}
    defaults:
        { _controller: JoliBlogBundle:List:index, page: 1 }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

current_time:
    path: /current-time
    defaults:
        _controller: AppBundle:Time:currentTime

square:
    path: /square/{n}
    defaults:
        _controller: AppBundle:Maths:square
